jwt: 
  secret: 'test'

server:
  port : 8090
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    url: jdbc:h2:file:C:\Users\dbeqiraj\git\Spring_Security\test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  h2:
    console:
      enabled: 'true'

      

#jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE